// 이벤트 등록 => 이벤트 구분
export const FETCH_RECIPE='FETCH_RECIPE'
export const FETCH_NEWS='FETCH_NEWS'
export const FETCH_CATEGORY='FETCH_CATEGORY'
export const FETCH_CATE_FOOD='FETCH_CATE_FOOD'
export const FETCH_FOOD_DETAIL='FETCH_FOOD_DETAIL'
export const FETCH_POP_FOOD='FETCH_POP_FOOD'
export const FETCH_RECOMMAND_FOOD='FETCH_RECOMMAND_FOOD'
